
openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: size
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        400:
          description: Mauvais paramètres
          content:
            application/json:
              schema:
                type: object