openapi: 3.0.3
info:
  title: Tasks API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /tasks:
    get:
      responses:
        200:
          description: Liste des taches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      responses:
        201:
          description: Taches créées
  /tasks/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Taches trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Taches non trouvée
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Tache supprimée
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean