openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /products:
    get:
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        200:
          description: Liste des produits
          content:

            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
    q:
      name: q
      in: query
      schema:
        type: string
  schemas:
      Product:
        type: object
        properties:
          name:
            type: string
          expiration_date:
            type: string
            format: date-time
          price:
            type: number